INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (665.0, 'Bonduelle vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (744.0, 'Calvaire vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (666.0, 'Pont Audibert vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (681.0, 'Stalingrad vers est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (679.0, 'Bd Malakoff vers Gare Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (699.0, 'Coteaux vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (787.0, '50 Otages Vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (788.0, '50 Otages Vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (700.0, 'Promenade de Bellevue vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (89.0, 'Coteaux vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (880.0, 'Madeleine vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (890.0, 'Pont de Pirmil vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (674.0, 'Pont Haudaudine vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (683.0, 'pont Anne de Bretagne vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (727.0, 'Pont Tabarly vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (747.0, 'Chemin de halage TortiÃ¨re vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (746.0, 'Chemin de halage TortiÃ¨re vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (943.0, 'Magellan vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (944.0, 'Magellan vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (1041.0, 'Guy Mollet vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (1042.0, 'Guy Mollet vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (668.0, 'De Gaulle vers sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (682.0, 'pont Anne de Bretagne vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (677.0, 'Pont Willy Brandt vers Malakoff');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (725.0, 'Pont Tabarly vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (945.0, 'Magellan vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (949.0, 'avenue de la LibÃ©ration vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (980.0, 'Pont Tabarly vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (995.0, 'Ceineray vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (1031.0, 'VN751A Vers St Leger les Vignes');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (667.0, 'EntrÃ©e pont Audibert vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (672.0, 'Pont de Pornic vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (786.0, '50 Otages Vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (847.0, 'EntrÃ©e pont Audibert vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (907.0, 'Stade vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (996.0, 'Van Iseghem vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (669.0, 'De Gaulle sortie ClÃ©menceau vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (673.0, 'Pont de Pornic vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (680.0, 'Stalingrad vers ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (676.0, 'Pont Willy Brandt vers Beaulieu');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (701.0, 'Promenade de Bellevue vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (743.0, 'Philippot vers ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (742.0, 'Philippot vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (785.0, '50 Otages Vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (889.0, 'Stade vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (946.0, 'Magellan vers Est');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (960.0, 'SoriniÃ¨res Vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (997.0, 'Van Iseghem vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (1032.0, 'VN vers SucÃ© sur Erdre');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (664.0, 'Bonduelle vers sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (670.0, 'Pont de Pirmil vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (675.0, 'Pont Haudaudine vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (745.0, 'Calvaire vers Ouest');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (881.0, 'Madeleine vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (950.0, 'avenue de la LibÃ©ration vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (959.0, 'SoriniÃ¨res Vers Sud');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (981.0, 'Pont Tabarly vers Nord');
INSERT INTO `compteurs` (`numero`, `libelle`) VALUES (994.0, 'Ceineray vers Est');
